const tourist_activities = [
    "Adventure tourism",
    "Archaeological site",
    "Archery",
    "Art museum",
    "Basketball",
    "Beach",
    "Beach volleyball",
    "Bungee jumping",
    "Botanical garden",
    "Cave or grotto",
    "Concert or show",
    "Culinary tour",
    "Cycling",
    "Ecotourism activities",
    "Flea market",
    "Fishing",
    "Football (Soccer)",
    "Golf",
    "Hiking",
    "Horseback riding",
    "Kayaking",
    "Local market",
    "Monument",
    "Mountain biking",
    "Martial arts",
    "National park",
    "Nightlife experience",
    "Ping Pong (Table tennis)",
    "Quaint old street",
    "Rock climbing",
    "Rafting",
    "Rappel",
    "Safari",
    "Scuba diving",
    "Shopping tourism",
    "Skating",
    "Skiing or snowboarding",
    "Snorkeling",
    "Surfing",
    "Tennis",
    "Water sport",
    "Waterfall or cascade",
    "Wine tasting",
    "Wine tourism",
    "Yoga",
    "Zoo or aquarium",
];

export default tourist_activities;